apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: openbao
spec:
  provider:
    vault:
      server: "https://192.168.68.77:8200"
      path: "platform"
      version: "v2"
      caBundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURKRENDQWd5Z0F3SUJBZ0lVY1NMTUZZd05lOC92Nm9pT05HVUROTWcyWURvd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0RqRU1NQW9HQTFVRUF3d0RZbUZ2TUI0WERUSTJNRGd3TkRJeU16TTFNVm9YRFRNMk1EZ3dNVEl5TXpNMQpNVm93RGpFTU1Bb0dBMVVFQXd3RFltRnZNSUlCSWpBTkJna3Foa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDCkFRRUFzcmFJMUNXWUtXMXdjOG9BUzUvVlFlUFpkaXNKcVVnNTBIWlpQRHo1aUE4a2dla3VOc25VWVVLbDlvZ0UKVGVyWURnMEV6dUVXU2paMjRURmlwQkxLZklBaVprQUg1UVowUEUyekQyZUozYlNrNmpwTXZqREJQbWc2cDd5OApHWnpwOHBSQnlRZk9WaWZQSGFoSUNxVUROZmUvUnVlMWxNa2JCczhqdjk3UWNmdHUxVDArNUdHaEd4NGpNQ2Q3CkIrN0I3ZWo0V1F4emhlNjlZWTAvN3FvZnoxaDl5cVJSRHRyazJQdGE1SFlMUXY4OUFvUTRWN0phYzk4Qm1pR1EKT2ZPa09NTmlJOFdaL2p4azdOVFJTbVFhT0VGNUJMWFZhRWE2L1ZkZVJXeFhDYUNmVVRCaFRXdmVWd1ZEZkRmMQpqaHErbFpoYTZrNmk0dXFtQWtMcXpRUVZod0lEQVFBQm8zb3dlREFkQmdOVkhRNEVGZ1FVNXlrUXAzUUZwbHlhCm9YdURIRWdLRkdlSDF3OHdId1lEVlIwakJCZ3dGb0FVNXlrUXAzUUZwbHlhb1h1REhFZ0tGR2VIMXc4d0R3WUQKVlIwVEFRSC9CQVV3QXdFQi96QWxCZ05WSFJFRUhqQWNod1RBcUVSTmh3Ui9BQUFCZ2dOaVlXK0NDV0poYnk1cwpiMk5oYkRBTkJna3Foa2lHOXcwQkFRc0ZBQU9DQVFFQXNnNmVtekRHVnVTeWF5L2x1UEpoMk1jVkFOT2FKN09qCjlHUnJ6Y1Y4TjUyMW5KTENMU091MWR6RTBqS3FVY0d0MU5yTWFXMTBucnJOK25CR1duRW9PbWs1SE8rYnZvY04Kdjl3NVRma2oreFhucEdYVG04K05qUi8rL0podDdDNEVObkZPbkpxdnVId2l2Y1ZFQ0Nnd2V4NFpOMGpQNHdmaQpwcXZNU1ZWVUcyeEI3UU1wOUVaZEh4bzdtb3Fvb0lneHE2bGZBejhiUHZ5NXZreEFsalNrQTJjaHhhMStRcENGCmF1cCtsUkRxWVhEbUh2V1pjL2tNSk1abEtTNGZuL2IrWkE0SEdUTXRxWkNPUjZSUHF3aW9ob016ODY1OFc2bTQKM1lOZGtCTldBWVVJemRuMW9qcFhzbnZHSE9NS0IreUx6bUpkVjEzOUxqbitYRURMRXpQMjd3PT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo="
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "eso"
          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets
