#!/bin/bash
# generate-ansible-config.sh — turn config.sh into the ansible inventory and
# the six VM declarations vm-ensure.yml / k3s-ensure.yml read.
#
# Everything this writes goes under ansible/generated/ and is git-ignored —
# it's a RENDERING of config.sh, not a thing to hand-edit or commit. Re-run
# any time config.sh changes; every other script in this platform sources
# config.sh and calls this first, so it's always current.
#
# Not a templating engine — config.sh is already plain bash, so this is
# just heredocs with variable substitution, same register as the rest of
# this platform's scripts.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PLATFORM_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
GENERATED_DIR="$PLATFORM_DIR/ansible/generated"

# shellcheck source=/dev/null
source "$PLATFORM_DIR/config.sh"

mkdir -p "$GENERATED_DIR/vars/vms"

# ── the inventory: 3 Proxmox hosts + 6 k3s VMs ────────────────────────────
cat > "$GENERATED_DIR/inventory.yml" <<EOF
# GENERATED by generate-ansible-config.sh from config.sh — do not hand-edit,
# re-run that script instead. Not committed (see .gitignore).
all:
  vars:
    ansible_ssh_private_key_file: "${PROXMOX_SSH_KEY}"
  children:
    proxmox:
      vars:
        ansible_user: root
      hosts:
        ${PROXMOX_HOST1_NAME}:
          ansible_host: ${PROXMOX_HOST1_ADDR}
        ${PROXMOX_HOST2_NAME}:
          ansible_host: ${PROXMOX_HOST2_ADDR}
        ${PROXMOX_HOST3_NAME}:
          ansible_host: ${PROXMOX_HOST3_ADDR}
    guests:
      hosts:
        ${PROXMOX_HOST1_NAME}-k3s:
          ansible_host: ${K3S_VM_HOST1_IP}
          ansible_user: ${VM_CIUSER}
        ${PROXMOX_HOST1_NAME}-k3s-test:
          ansible_host: ${K3S_VM_HOST1_TEST_IP}
          ansible_user: ${VM_CIUSER}
        ${PROXMOX_HOST2_NAME}-k3s:
          ansible_host: ${K3S_VM_HOST2_IP}
          ansible_user: ${VM_CIUSER}
        ${PROXMOX_HOST2_NAME}-k3s-test:
          ansible_host: ${K3S_VM_HOST2_TEST_IP}
          ansible_user: ${VM_CIUSER}
        ${PROXMOX_HOST3_NAME}-k3s:
          ansible_host: ${K3S_VM_HOST3_IP}
          ansible_user: ${VM_CIUSER}
        ${PROXMOX_HOST3_NAME}-k3s-test:
          ansible_host: ${K3S_VM_HOST3_TEST_IP}
          ansible_user: ${VM_CIUSER}
EOF

# ── one VM declaration per k3s node ────────────────────────────────────────
# write_vm_decl <file> <name> <vmid> <cores> <mem_mb> <disk_gb> <ip> <k3s_role> <server_url> <taint> <cluster_cidr> <service_cidr>
write_vm_decl() {
  local file="$1" name="$2" vmid="$3" cores="$4" mem="$5" disk="$6" ip="$7" \
        role="$8" server_url="$9" taint="${10}" ccidr="${11}" scidr="${12}"
  cat > "$file" <<EOF
# GENERATED from config.sh by generate-ansible-config.sh — do not hand-edit.
vm:
  name: ${name}
  vmid: ${vmid}
  cores: ${cores}
  memory: ${mem}
  disk_gb: ${disk}
  storage: ${PROXMOX_STORAGE}
  bridge: vmbr0
  cloud_image: ${VM_CLOUD_IMAGE}
  cloud_image_url: "${VM_CLOUD_IMAGE_URL}"
  ip: "${ip}/${NETWORK_PREFIX_LENGTH}"
  gateway: "${NETWORK_GATEWAY}"
  nameserver: "${NETWORK_DNS}"
  searchdomain: ${NETWORK_SEARCH_DOMAIN}
  ciuser: ${VM_CIUSER}

k3s:
  role: ${role}
  version: "${K3S_VERSION}"
EOF
  [[ -n "$server_url" ]] && echo "  server_url: \"${server_url}\"" >> "$file"
  [[ "$taint" == "true" ]] && echo "  taint_control_plane_only: true" >> "$file"
  if [[ -n "$ccidr" ]]; then
    echo "  cluster_cidr: \"${ccidr}\"" >> "$file"
    echo "  service_cidr: \"${scidr}\"" >> "$file"
  fi
}

PROD_SERVER_URL="https://${K3S_VM_HOST1_IP}:6443"
TEST_SERVER_URL="https://${K3S_VM_HOST1_TEST_IP}:6443"

write_vm_decl "$GENERATED_DIR/vars/vms/${PROXMOX_HOST1_NAME}-k3s.yml" \
  "${PROXMOX_HOST1_NAME}-k3s" "$K3S_VM_HOST1_VMID" "$K3S_VM_HOST1_CORES" \
  "$K3S_VM_HOST1_MEMORY_MB" "$K3S_VM_HOST1_DISK_GB" "$K3S_VM_HOST1_IP" \
  "init" "" "false" "" ""

write_vm_decl "$GENERATED_DIR/vars/vms/${PROXMOX_HOST1_NAME}-k3s-test.yml" \
  "${PROXMOX_HOST1_NAME}-k3s-test" "$K3S_VM_HOST1_TEST_VMID" "$K3S_VM_HOST1_TEST_CORES" \
  "$K3S_VM_HOST1_TEST_MEMORY_MB" "$K3S_VM_HOST1_TEST_DISK_GB" "$K3S_VM_HOST1_TEST_IP" \
  "init" "" "false" "$K3S_TEST_CLUSTER_CIDR" "$K3S_TEST_SERVICE_CIDR"

write_vm_decl "$GENERATED_DIR/vars/vms/${PROXMOX_HOST2_NAME}-k3s.yml" \
  "${PROXMOX_HOST2_NAME}-k3s" "$K3S_VM_HOST2_VMID" "$K3S_VM_HOST2_CORES" \
  "$K3S_VM_HOST2_MEMORY_MB" "$K3S_VM_HOST2_DISK_GB" "$K3S_VM_HOST2_IP" \
  "join" "$PROD_SERVER_URL" "false" "" ""

write_vm_decl "$GENERATED_DIR/vars/vms/${PROXMOX_HOST2_NAME}-k3s-test.yml" \
  "${PROXMOX_HOST2_NAME}-k3s-test" "$K3S_VM_HOST2_TEST_VMID" "$K3S_VM_HOST2_TEST_CORES" \
  "$K3S_VM_HOST2_TEST_MEMORY_MB" "$K3S_VM_HOST2_TEST_DISK_GB" "$K3S_VM_HOST2_TEST_IP" \
  "join" "$TEST_SERVER_URL" "false" "$K3S_TEST_CLUSTER_CIDR" "$K3S_TEST_SERVICE_CIDR"

write_vm_decl "$GENERATED_DIR/vars/vms/${PROXMOX_HOST3_NAME}-k3s.yml" \
  "${PROXMOX_HOST3_NAME}-k3s" "$K3S_VM_HOST3_VMID" "$K3S_VM_HOST3_CORES" \
  "$K3S_VM_HOST3_MEMORY_MB" "$K3S_VM_HOST3_DISK_GB" "$K3S_VM_HOST3_IP" \
  "join" "$PROD_SERVER_URL" "${K3S_VM_HOST3_CONTROL_PLANE_ONLY:-false}" "" ""

write_vm_decl "$GENERATED_DIR/vars/vms/${PROXMOX_HOST3_NAME}-k3s-test.yml" \
  "${PROXMOX_HOST3_NAME}-k3s-test" "$K3S_VM_HOST3_TEST_VMID" "$K3S_VM_HOST3_TEST_CORES" \
  "$K3S_VM_HOST3_TEST_MEMORY_MB" "$K3S_VM_HOST3_TEST_DISK_GB" "$K3S_VM_HOST3_TEST_IP" \
  "join" "$TEST_SERVER_URL" "false" "$K3S_TEST_CLUSTER_CIDR" "$K3S_TEST_SERVICE_CIDR"

# ── one guest declaration per configured core service, all on host1 ───────
# 🔵 Concentrated on host1 by default, not ranked by hardware strength — see config.sh-template's
# own comment. VMIDs/sizing below match the values proven on the reference lab
# (platform/MIGRATION-services.md); override by editing this script if your hardware differs.
mkdir -p "$GENERATED_DIR/vars/core-services"

write_core_service() {
  local name="$1" vmid="$2" cores="$3" mem="$4" swap="$5" startup="$6" \
        features="$7" rootfs_gb="$8" mount_mp="$9" mount_gb="${10}" recordsize="${11}" role="${12}"
  local file="$GENERATED_DIR/vars/core-services/${name}.yml"
  cat > "$file" <<EOF
# GENERATED from config.sh by generate-ansible-config.sh — do not hand-edit.
guest:
  name: ${name}
  vmid: ${vmid}
  kind: lxc
  ostype: debian
  template: "debian-13-standard_13.6-1_amd64.tar.zst"
  cores: ${cores}
  memory: ${mem}
  swap: ${swap}
  unprivileged: true
EOF
  [[ -n "$features" ]] && echo "  features: \"${features}\"" >> "$file"
  cat >> "$file" <<EOF
  onboot: true
  startup: "${startup}"
  rootfs:
    storage: ${PROXMOX_STORAGE}
    size_gb: ${rootfs_gb}
EOF
  if [[ -n "$mount_mp" ]]; then
    cat >> "$file" <<EOF
  mounts:
    - id: mp0
      storage: ${PROXMOX_STORAGE}
      size_gb: ${mount_gb}
      mountpoint: ${mount_mp}
EOF
    [[ -n "$recordsize" ]] && echo "      zfs_recordsize: ${recordsize}" >> "$file"
  fi
  cat >> "$file" <<EOF
  nets:
    - id: net0
      bridge: vmbr0
      ip: dhcp

service:
  role: ${role}
  playbook: playbooks/service-${name}.yml
  health: vars/${name}-health.yml
EOF
}

for svc in $CORE_SERVICES; do
  case "$svc" in
    pg)       write_core_service pg       405 4 8192 1024 "order=4" ""                  8  /var/lib/postgresql 200 16K postgres ;;
    bao)      write_core_service bao      408 2 1024 512  "order=2" ""                  8  /var/lib/openbao    10  ""  bao ;;
    garage)   write_core_service garage   407 2 2048 512  "order=3" "nesting=1,keyctl=1" 8  /var/lib/garage     100 ""  garage ;;
    registry) write_core_service registry 409 2 1024 512  "order=1" "nesting=1,keyctl=1" 8  /var/lib/registry   60  ""  registry ;;
    nas)      write_core_service nas      404 2 1024 512  "order=3" ""                  8  /srv/data           32  ""  nas ;;
    *) echo "⚠️  Unknown core service '$svc' in CORE_SERVICES — skipped" >&2 ;;
  esac
done

# ── per-service secrets/site-data, generated once and reused on every re-run ───────────────────
# 🔴 SECRETS LIVE ONLY HERE, gitignored (ansible/generated/), never in a committed declaration —
# same rule config.sh's own PROXMOX_SSH_KEY already follows. garage's role refuses to run without
# these (no sane default — a generated-and-forgotten credential is nobody's idea of a secret
# store); nas's role refuses to run without at least one user/share (site data, not role data).
EXTRA_VARS_FILE="$GENERATED_DIR/vars/core-services/_extra-vars.yml"
{
  echo "# GENERATED by generate-ansible-config.sh — secrets + site data, gitignored. Do not commit."
  for svc in $CORE_SERVICES; do
    case "$svc" in
      garage)
        if [[ ! -f "$EXTRA_VARS_FILE" ]] || ! grep -q "^garage_access_key:" "$EXTRA_VARS_FILE" 2>/dev/null; then
          echo "garage_access_key: \"GK$(openssl rand -hex 12)\""
          echo "garage_secret_key: \"$(openssl rand -hex 32)\""
          echo "garage_rpc_secret: \"$(openssl rand -hex 32)\""
        fi
        ;;
      nas)
        cat <<EOF
nas_groups:
  - { name: data, gid: 2000 }
nas_users:
  - { name: labowner, uid: 2000, group: data, comment: "default nas account - change the password with smbpasswd" }
nas_shares:
  - { name: data, comment: "default share", path: /srv/data, valid_users: labowner, create_mask: "0660", directory_mask: "02770", force_group: data }
EOF
        ;;
    esac
  done
} > "${EXTRA_VARS_FILE}.new"
# Preserve a previously-generated garage secret across re-runs (regenerating it would orphan the
# already-bootstrapped credential on a live guest) — only write secrets that don't already exist.
if [[ -f "$EXTRA_VARS_FILE" ]]; then
  grep "^garage_" "$EXTRA_VARS_FILE" > /tmp/.garage-secrets.$$ 2>/dev/null || true
  if [[ -s /tmp/.garage-secrets.$$ ]]; then
    grep -v "^garage_" "${EXTRA_VARS_FILE}.new" > /tmp/.extra-rest.$$
    cat /tmp/.extra-rest.$$ /tmp/.garage-secrets.$$ > "${EXTRA_VARS_FILE}.new"
    rm -f /tmp/.extra-rest.$$
  fi
  rm -f /tmp/.garage-secrets.$$
fi
mv "${EXTRA_VARS_FILE}.new" "$EXTRA_VARS_FILE"

echo "✓ Generated ansible/generated/inventory.yml, 6 VM declarations under ansible/generated/vars/vms/,"
echo "  and $(echo $CORE_SERVICES | wc -w) core-service declaration(s) under ansible/generated/vars/core-services/"
