#!/bin/bash
# test-generated-json.sh - Validate generated JSON documentation files
#
# Tests the JSON files generated by uis-docs.sh
#
# Prerequisites:
#   - Run 'uis docs generate' first to create JSON files
#   - jq must be installed for validation

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TESTS_DIR="$(dirname "$SCRIPT_DIR")"
UIS_DIR="$(dirname "$TESTS_DIR")"

# Source test framework
source "$TESTS_DIR/lib/test-framework.sh"

# Auto-detect data directory
_detect_data_dir() {
    # Container path
    if [[ -d "/mnt/urbalurbadisk/website/src/data" ]]; then
        echo "/mnt/urbalurbadisk/website/src/data"
        return 0
    fi

    # Host path: derive from script location
    local base_dir
    base_dir="$(cd "$UIS_DIR/../.." && pwd)"
    if [[ -d "$base_dir/website/src/data" ]]; then
        echo "$base_dir/website/src/data"
        return 0
    fi

    # Fallback
    echo "./website/src/data"
}

DATA_DIR="${DATA_DIR:-$(_detect_data_dir)}"

print_test_section "JSON Validation Tests"
echo ""
echo "Data directory: $DATA_DIR"
echo ""

# ============================================================
# File Existence Tests
# ============================================================

start_test "services.json exists"
if [[ -f "$DATA_DIR/services.json" ]]; then
    pass_test
else
    skip_test "File not found - run 'uis docs generate' first"
fi

start_test "categories.json exists"
if [[ -f "$DATA_DIR/categories.json" ]]; then
    pass_test
else
    skip_test "File not found - run 'uis docs generate' first"
fi

start_test "tools.json exists"
if [[ -f "$DATA_DIR/tools.json" ]]; then
    pass_test
else
    skip_test "File not found - run 'uis docs generate' first"
fi

# ============================================================
# JSON Validity Tests
# ============================================================

# Check if jq is available
if ! command -v jq &>/dev/null; then
    echo ""
    echo "WARNING: jq not installed, skipping JSON validity tests"
    print_summary
    exit 0
fi

start_test "services.json is valid JSON"
if [[ -f "$DATA_DIR/services.json" ]]; then
    if jq . "$DATA_DIR/services.json" >/dev/null 2>&1; then
        pass_test
    else
        fail_test "Invalid JSON syntax"
    fi
else
    skip_test "File not found"
fi

start_test "categories.json is valid JSON"
if [[ -f "$DATA_DIR/categories.json" ]]; then
    if jq . "$DATA_DIR/categories.json" >/dev/null 2>&1; then
        pass_test
    else
        fail_test "Invalid JSON syntax"
    fi
else
    skip_test "File not found"
fi

start_test "tools.json is valid JSON"
if [[ -f "$DATA_DIR/tools.json" ]]; then
    if jq . "$DATA_DIR/tools.json" >/dev/null 2>&1; then
        pass_test
    else
        fail_test "Invalid JSON syntax"
    fi
else
    skip_test "File not found"
fi

# ============================================================
# Content Tests
# ============================================================

start_test "services.json has services array"
if [[ -f "$DATA_DIR/services.json" ]]; then
    if jq -e '.services' "$DATA_DIR/services.json" >/dev/null 2>&1; then
        pass_test
    else
        fail_test "Missing 'services' array"
    fi
else
    skip_test "File not found"
fi

start_test "services.json has at least one service"
if [[ -f "$DATA_DIR/services.json" ]]; then
    count=$(jq '.services | length' "$DATA_DIR/services.json" 2>/dev/null || echo 0)
    if [[ "$count" -gt 0 ]]; then
        pass_test "$count services found"
    else
        fail_test "No services found"
    fi
else
    skip_test "File not found"
fi

start_test "categories.json has categories array"
if [[ -f "$DATA_DIR/categories.json" ]]; then
    if jq -e '.categories' "$DATA_DIR/categories.json" >/dev/null 2>&1; then
        pass_test
    else
        fail_test "Missing 'categories' array"
    fi
else
    skip_test "File not found"
fi

start_test "categories.json has at least one category"
if [[ -f "$DATA_DIR/categories.json" ]]; then
    count=$(jq '.categories | length' "$DATA_DIR/categories.json" 2>/dev/null || echo 0)
    if [[ "$count" -gt 0 ]]; then
        pass_test "$count categories found"
    else
        fail_test "No categories found"
    fi
else
    skip_test "File not found"
fi

start_test "tools.json has tools array"
if [[ -f "$DATA_DIR/tools.json" ]]; then
    if jq -e '.tools' "$DATA_DIR/tools.json" >/dev/null 2>&1; then
        pass_test
    else
        fail_test "Missing 'tools' array"
    fi
else
    skip_test "File not found"
fi

start_test "tools.json has at least one tool"
if [[ -f "$DATA_DIR/tools.json" ]]; then
    count=$(jq '.tools | length' "$DATA_DIR/tools.json" 2>/dev/null || echo 0)
    if [[ "$count" -gt 0 ]]; then
        pass_test "$count tools found"
    else
        fail_test "No tools found"
    fi
else
    skip_test "File not found"
fi

# ============================================================
# Schema Validation Tests
# ============================================================

start_test "Each service has required fields (id, name, category)"
if [[ -f "$DATA_DIR/services.json" ]]; then
    invalid=$(jq '[.services[] | select(.id == null or .name == null or .category == null)] | length' "$DATA_DIR/services.json" 2>/dev/null || echo -1)
    if [[ "$invalid" == "0" ]]; then
        pass_test
    else
        fail_test "$invalid services missing required fields"
    fi
else
    skip_test "File not found"
fi

start_test "Each category has required fields (id, name, order)"
if [[ -f "$DATA_DIR/categories.json" ]]; then
    invalid=$(jq '[.categories[] | select(.id == null or .name == null or .order == null)] | length' "$DATA_DIR/categories.json" 2>/dev/null || echo -1)
    if [[ "$invalid" == "0" ]]; then
        pass_test
    else
        fail_test "$invalid categories missing required fields"
    fi
else
    skip_test "File not found"
fi

start_test "Each tool has required fields (id, name)"
if [[ -f "$DATA_DIR/tools.json" ]]; then
    invalid=$(jq '[.tools[] | select(.id == null or .name == null)] | length' "$DATA_DIR/tools.json" 2>/dev/null || echo -1)
    if [[ "$invalid" == "0" ]]; then
        pass_test
    else
        fail_test "$invalid tools missing required fields"
    fi
else
    skip_test "File not found"
fi

# ============================================================
# Summary
# ============================================================

# ---------------------------------------------------------------------------
# A named logo must be a logo that exists.
#
# services.json carries SCRIPT_LOGO verbatim, and the site renders
# /img/services/<logo>. A name with no file behind it is a broken image on the
# catalogue — visible to every visitor and to nobody running tests. Added
# 2026-09-19 when oauth2-proxy got its logo; it applies to every service.
# ---------------------------------------------------------------------------

_LOGO_DIR="$(cd "$DATA_DIR/../../static/img/services" 2>/dev/null && pwd || true)"

start_test "the logo directory the site serves from exists"
if [[ -n "$_LOGO_DIR" && -d "$_LOGO_DIR" ]]; then
    pass_test
else
    fail_test "no static/img/services next to the data dir — the check below would vacuously pass"
fi

start_test "every service that names a logo has that file on disk"
# Positive control first: an empty result here would otherwise be read as
# "all logos fine" when it may mean "jq matched nothing".
_named=$(jq -r '.services[] | select((.logo // "") != "") | "\(.id) \(.logo)"' "$DATA_DIR/services.json")
if [[ -z "$_named" ]]; then
    fail_test "no service names a logo at all — the query is wrong, not the data"
else
    _missing=""
    while read -r _id _logo; do
        [[ -z "$_id" ]] && continue
        [[ -f "$_LOGO_DIR/$_logo" ]] || _missing="$_missing $_id:$_logo"
    done <<< "$_named"
    if [[ -z "$_missing" ]]; then
        pass_test
    else
        fail_test "named but missing —$_missing"
    fi
fi

print_summary
