#!/bin/bash
# generate-ansible-config.sh — turn config.sh into the ansible inventory and
# the six VM declarations vm-ensure.yml / k3s-ensure.yml read.
#
# Everything this writes goes under ansible/generated/ and is git-ignored —
# it's a RENDERING of config.sh, not a thing to hand-edit or commit. Re-run
# any time config.sh changes; every other script in this platform sources
# config.sh and calls this first, so it's always current.
#
# Not a templating engine — config.sh is already plain bash, so this is
# just heredocs with variable substitution, same register as the rest of
# this platform's scripts.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PLATFORM_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
GENERATED_DIR="$PLATFORM_DIR/ansible/generated"

# shellcheck source=/dev/null
source "$PLATFORM_DIR/config.sh"

mkdir -p "$GENERATED_DIR/vars/vms"

# ── the inventory: 3 Proxmox hosts + 6 k3s VMs ────────────────────────────
cat > "$GENERATED_DIR/inventory.yml" <<EOF
# GENERATED by generate-ansible-config.sh from config.sh — do not hand-edit,
# re-run that script instead. Not committed (see .gitignore).
all:
  vars:
    ansible_user: tec
    ansible_ssh_private_key_file: "${PROXMOX_SSH_KEY}"
  children:
    proxmox:
      vars:
        ansible_user: root
      hosts:
        ${PROXMOX_HOST1_NAME}:
          ansible_host: ${PROXMOX_HOST1_ADDR}
        ${PROXMOX_HOST2_NAME}:
          ansible_host: ${PROXMOX_HOST2_ADDR}
        ${PROXMOX_HOST3_NAME}:
          ansible_host: ${PROXMOX_HOST3_ADDR}
    guests:
      hosts:
        ${PROXMOX_HOST1_NAME}-k3s:
          ansible_host: ${K3S_VM_HOST1_IP}
          ansible_user: ${VM_CIUSER}
        ${PROXMOX_HOST1_NAME}-k3s-test:
          ansible_host: ${K3S_VM_HOST1_TEST_IP}
          ansible_user: ${VM_CIUSER}
        ${PROXMOX_HOST2_NAME}-k3s:
          ansible_host: ${K3S_VM_HOST2_IP}
          ansible_user: ${VM_CIUSER}
        ${PROXMOX_HOST2_NAME}-k3s-test:
          ansible_host: ${K3S_VM_HOST2_TEST_IP}
          ansible_user: ${VM_CIUSER}
        ${PROXMOX_HOST3_NAME}-k3s:
          ansible_host: ${K3S_VM_HOST3_IP}
          ansible_user: ${VM_CIUSER}
        ${PROXMOX_HOST3_NAME}-k3s-test:
          ansible_host: ${K3S_VM_HOST3_TEST_IP}
          ansible_user: ${VM_CIUSER}
EOF

# ── one VM declaration per k3s node ────────────────────────────────────────
# write_vm_decl <file> <name> <vmid> <cores> <mem_mb> <disk_gb> <ip> <k3s_role> <server_url> <taint> <cluster_cidr> <service_cidr>
write_vm_decl() {
  local file="$1" name="$2" vmid="$3" cores="$4" mem="$5" disk="$6" ip="$7" \
        role="$8" server_url="$9" taint="${10}" ccidr="${11}" scidr="${12}"
  cat > "$file" <<EOF
# GENERATED from config.sh by generate-ansible-config.sh — do not hand-edit.
vm:
  name: ${name}
  vmid: ${vmid}
  cores: ${cores}
  memory: ${mem}
  disk_gb: ${disk}
  storage: ${PROXMOX_STORAGE}
  bridge: vmbr0
  cloud_image: ${VM_CLOUD_IMAGE}
  cloud_image_url: "${VM_CLOUD_IMAGE_URL}"
  ip: "${ip}/${NETWORK_PREFIX_LENGTH}"
  gateway: "${NETWORK_GATEWAY}"
  nameserver: "${NETWORK_DNS}"
  searchdomain: ${NETWORK_SEARCH_DOMAIN}
  ciuser: ${VM_CIUSER}

k3s:
  role: ${role}
  version: "${K3S_VERSION}"
EOF
  [[ -n "$server_url" ]] && echo "  server_url: \"${server_url}\"" >> "$file"
  [[ "$taint" == "true" ]] && echo "  taint_control_plane_only: true" >> "$file"
  if [[ -n "$ccidr" ]]; then
    echo "  cluster_cidr: \"${ccidr}\"" >> "$file"
    echo "  service_cidr: \"${scidr}\"" >> "$file"
  fi
}

PROD_SERVER_URL="https://${K3S_VM_HOST1_IP}:6443"
TEST_SERVER_URL="https://${K3S_VM_HOST1_TEST_IP}:6443"

write_vm_decl "$GENERATED_DIR/vars/vms/${PROXMOX_HOST1_NAME}-k3s.yml" \
  "${PROXMOX_HOST1_NAME}-k3s" "$K3S_VM_HOST1_VMID" "$K3S_VM_HOST1_CORES" \
  "$K3S_VM_HOST1_MEMORY_MB" "$K3S_VM_HOST1_DISK_GB" "$K3S_VM_HOST1_IP" \
  "init" "" "false" "" ""

write_vm_decl "$GENERATED_DIR/vars/vms/${PROXMOX_HOST1_NAME}-k3s-test.yml" \
  "${PROXMOX_HOST1_NAME}-k3s-test" "$K3S_VM_HOST1_TEST_VMID" "$K3S_VM_HOST1_TEST_CORES" \
  "$K3S_VM_HOST1_TEST_MEMORY_MB" "$K3S_VM_HOST1_TEST_DISK_GB" "$K3S_VM_HOST1_TEST_IP" \
  "init" "" "false" "$K3S_TEST_CLUSTER_CIDR" "$K3S_TEST_SERVICE_CIDR"

write_vm_decl "$GENERATED_DIR/vars/vms/${PROXMOX_HOST2_NAME}-k3s.yml" \
  "${PROXMOX_HOST2_NAME}-k3s" "$K3S_VM_HOST2_VMID" "$K3S_VM_HOST2_CORES" \
  "$K3S_VM_HOST2_MEMORY_MB" "$K3S_VM_HOST2_DISK_GB" "$K3S_VM_HOST2_IP" \
  "join" "$PROD_SERVER_URL" "false" "" ""

write_vm_decl "$GENERATED_DIR/vars/vms/${PROXMOX_HOST2_NAME}-k3s-test.yml" \
  "${PROXMOX_HOST2_NAME}-k3s-test" "$K3S_VM_HOST2_TEST_VMID" "$K3S_VM_HOST2_TEST_CORES" \
  "$K3S_VM_HOST2_TEST_MEMORY_MB" "$K3S_VM_HOST2_TEST_DISK_GB" "$K3S_VM_HOST2_TEST_IP" \
  "join" "$TEST_SERVER_URL" "false" "$K3S_TEST_CLUSTER_CIDR" "$K3S_TEST_SERVICE_CIDR"

write_vm_decl "$GENERATED_DIR/vars/vms/${PROXMOX_HOST3_NAME}-k3s.yml" \
  "${PROXMOX_HOST3_NAME}-k3s" "$K3S_VM_HOST3_VMID" "$K3S_VM_HOST3_CORES" \
  "$K3S_VM_HOST3_MEMORY_MB" "$K3S_VM_HOST3_DISK_GB" "$K3S_VM_HOST3_IP" \
  "join" "$PROD_SERVER_URL" "${K3S_VM_HOST3_CONTROL_PLANE_ONLY:-false}" "" ""

write_vm_decl "$GENERATED_DIR/vars/vms/${PROXMOX_HOST3_NAME}-k3s-test.yml" \
  "${PROXMOX_HOST3_NAME}-k3s-test" "$K3S_VM_HOST3_TEST_VMID" "$K3S_VM_HOST3_TEST_CORES" \
  "$K3S_VM_HOST3_TEST_MEMORY_MB" "$K3S_VM_HOST3_TEST_DISK_GB" "$K3S_VM_HOST3_TEST_IP" \
  "join" "$TEST_SERVER_URL" "false" "$K3S_TEST_CLUSTER_CIDR" "$K3S_TEST_SERVICE_CIDR"

echo "✓ Generated ansible/generated/inventory.yml and 6 VM declarations under ansible/generated/vars/vms/"
